<!--Regole di mappatura (di schematizzazione)-->
<!ELEMENT Scontrino (Intestazione, Corpo, DidascaliaTitolo, DidascaliaCorpo)>
<!ELEMENT Intestazione (nomeNegozio, via) >
<!ELEMENT nomeNegozio (#PCDATA) >
<!ELEMENT via (#PCDATA) >
<!ELEMENT Corpo (TitoloTabella, CorpoTabella, PiedeTabella)>
<!ELEMENT TitoloTabella (colonnaT1, colonnaT2, colonnaT3)>
<!ELEMENT CorpoTabella (colonnaC1, colonnaC2, colonnaC3)>
<!ELEMENT colonnaT1 (#PCDATA) >
<!ELEMENT colonnaT2 (#PCDATA) >
<!ELEMENT colonnaT3 (#PCDATA) >
<!ELEMENT colonnaC1 (#PCDATA) >
<!ELEMENT colonnaC2 (#PCDATA) >
<!ELEMENT colonnaC3 (#PCDATA) >
<!ELEMENT PiedeTabella (colonnaPT, colonnaPC)>
<!ELEMENT colonnaPT (#PCDATA) >
<!ELEMENT colonnaPC (#PCDATA) >
<!ELEMENT DidascaliaTitolo (colonnaDT, colonnaNT)>
<!ELEMENT DidascaliaCorpo (colonnaDC, colonnaNC)>
<!ELEMENT colonnaDT (#PCDATA) >
<!ELEMENT colonnaNT (#PCDATA) >
<!ELEMENT colonnaDC (#PCDATA) >
<!ELEMENT colonnaNC (#PCDATA) >